
services:
  backend:
    build: ./backend
    container_name: job-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped

  # frontend:
  #   build: ./frontend
  #   container_name: job-frontend
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - ./frontend/public:/app/public
  #   restart: unless-stopped
