apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: {{ .Values.fastapi.port }}
      targetPort: {{ .Values.fastapi.port }}
      nodePort: 32232
